name: CI/CD Pipeline for GitHub Pages

on:
  push:
    branches:
      - main  # Runs only on pushes to main branch

jobs:
  validate:
    name: Validate HTML & CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: '.' # Root folder

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Deploy entire root folder

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
